# Generated by Django 3.1.5 on 2021-01-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_vacancies_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
