# Generated by Django 3.1.4 on 2021-01-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20210108_1318'),
        ('careers', '0006_practice_status'),
    ]

    operations = [
    ]
